### PR TITLE
Add zeroconf as default mDNS implementation

### LINKED ISSUE #10: spydaap uses pybonjour which cannot be installed using pip because upstream is gone
Spydaap requires pybonjour if avahi is not present. pybonjour cannot be installed through pip, probably because its upstream is gone.

### Steps to Reproduce (for bugs)
1.  run `pip install --user pybonjour`

### Expected Behavior
Install a working copy of pybonjour.

### Current Behavior
```
$ pip install --user pybonjour
Collecting pybonjour
  Could not find a version that satisfies the requirement pybonjour (from versions: )
No matching distribution found for pybonjour
```

### Possible Solution
a) use a different Zeroconf/bonjour/mDNS implementation – there's plenty out there. Requires a fix in spydaap.

b) create our own "upstream". Requires getting the code from somewhere. Requires maintaining the code.

c) kill the dependency on pybonjour and rely on everyone having (or installing) avahi

### Additional info
This issue came up in https://github.com/egh/spydaap/pull/7#issuecomment-341946054 and was later referenced to in https://github.com/exaile/exaile/pull/445#issuecomment-342895195

avahi uses native code and may be unavailable or hard to install on Windows, MacOS and any other non-Linux platform. We may want to have a pure python implementation of Zeroconf/bonjour/mDNS.

cc'ing @virtuald

### PR DESCRIPTION
**Pull request by virtuald**
- Fixes #10

.. I'm able to see the information published via `dns-sd`, and I can ping the published service name. However, I don't really know how to test the actual DAAP thing, so who knows if it works. But, better than the current situation I suppose?

### CODE REVIEW

**Comment by virtuald** [comment]
@genodeftest

**Comment by genodeftest** [comment]
Suggestions how to test (minimum test):
1. run two exaile instances, one as daap server, one as daap client, preferably on two different computers in the same local network.
2. Try each combination of avahi and zeroconf, i.e. have the server or the client use either of those versions.
3. Play a few songs on each test

This'll take a while to setup and test and I can't do that in the next few days as I'm writing on my master thesis.

**Comment by genodeftest** [comment]
I'd remove the pybonjour bindings completely. Since upstream is gone I don't even know where to get the source code and since has been unmaintained for years we probably don't want to use it anyway. Code that cannot be used because of missing dependencies is of no use.

**Comment by egh** [comment]
You can also use rhythmbox, which has a daap client.

Or run `avahi-browse -ar` to browse published servers.

I tried running rhythmbox locally and I got the following error in spydaap with this branch:
```
spydaap server started (use --help for more options).  Press Ctrl-C to exit.
Traceback (most recent call last):
  File "/home/egh/.virtualenvs/spydaap/bin/spydaap", line 11, in <module>
    load_entry_point('spydaap==0.2', 'console_scripts', 'spydaap')()
  File "build/bdist.linux-x86_64/egg/spydaap/cli.py", line 206, in main
  File "build/bdist.linux-x86_64/egg/spydaap/cli.py", line 102, in really_main
  File "build/bdist.linux-x86_64/egg/spydaap/zeroconfimpl.py", line 163, in publish
  File "build/bdist.linux-x86_64/egg/spydaap/zeroconfimpl.py", line 72, in publish
AttributeError: 'module' object has no attribute 'get_all_addresses'
```

**Comment by egh** [comment]
I see no reason to retain pybonjour if it is no longer available.

**Comment by virtuald** [comment]
@egh that's a strange error, what version of zeroconf is installed?

**Comment by virtuald** [comment]
Ha, rhythmbox worked flawlessly. That's fantastic.

Updated this PR to remove pybonjour.

**Comment by virtuald** [comment]
@egh given that you're running from the build directory as an egg, I'd recommend deleting the directory and reinstalling spydaap. Most likely it's trying to use the previous zeroconf module in spydaap instead of the external zeroconf (absolute import issues related to python 2.7 I'm guessing). That's why I renamed it to zeroconfimpl.

**Comment by egh** [comment]
@virtuald This was a clean install, but it's been a while since I used spydaap :) so I'll take a look.

**Comment by egh** [comment]
@virtuald This is using the spydaap executable, not the embedded version in exaile.

**Comment by virtuald** [comment]
Yes, I used the spydaap program directly.

**Comment by virtuald** [comment]
Sounds like this is good to merge then?

**Comment by egh** [comment]
Looks good to me! Thank you.

**Pull request merged**
